VeryGoodOpenSource/very_good_templates

.github/workflows/very_good_dart_package.yaml, very_good_dart_package/__brick__/{{project_name.snakeCase()}}/pubspec.yaml
=> feat(very_good_dart_package)!: update to Dart 3.3.0

.github/workflows/very_good_flame_game.yaml, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/pubspec.yaml
=> feat(very_good_flame)!: update to Flutter 3.19.0

.github/workflows/very_good_core.yaml, very_good_core/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_core/hooks/pubspec.yaml
=> feat(very_good_core)!: update to Flutter 3.19.0

.github/workflows/very_good_dart_cli.yaml, very_good_dart_cli/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_dart_cli/hooks/pubspec.yaml
=> feat(very_good_dart_cli)!: update to Dart 3.3.0

.github/workflows/very_good_wear_app.yaml, very_good_wear_app/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_wear_app/e2e/pubspec.yaml, very_good_wear_app/hooks/pubspec.yaml
=> feat(very_good_wear_app)!: update to Flutter 3.19.0

very_good_core/brick.yaml, very_good_dart_cli/brick.yaml, very_good_dart_package/brick.yaml, very_good_docs_site/brick.yaml, very_good_flame_game/brick.yaml, very_good_flutter_package/brick.yaml, very_good_wear_app/brick.yaml
Sets min Mason environment to the latest.
=> chore: update bricks to Mason 0.1.0-dev.52

.github/labels.yml, .github/workflows/sync_labels.yaml
=> chore: add label sync action

README.md
Adds the very_good_flutter_plugin to the README table.
=> docs: add very_good_flutter_plugin to table

very_good_flutter_plugin/brick.yaml
=> chore(very_good_flutter_plugin): update repository url

very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/.github/workflows/{{#android}}{{project_name.snakeCase()}}_android.yaml{{/android}}, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/.github/workflows/{{#ios}}{{project_name.snakeCase()}}_ios.yaml{{/ios}}, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/.github/workflows/{{#linux}}{{project_name.snakeCase()}}_linux.yaml{{/linux}}, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/.github/workflows/{{#macos}}{{project_name.snakeCase()}}_macos.yaml{{/macos}}, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/.github/workflows/{{#web}}{{project_name.snakeCase()}}_web.yaml{{/web}}, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/.github/workflows/{{#windows}}{{project_name.snakeCase()}}_windows.yaml{{/windows}}, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/.github/workflows/{{project_name.snakeCase()}}.yaml, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/.github/workflows/{{project_name.snakeCase()}}_platform_interface.yaml, very_good_flutter_plugin/hooks/pre_gen.dart
=> refactor(very_good_flutter_plugin): template flutterVersion

very_good_flutter_plugin/hooks/lib/version.dart, very_good_flutter_plugin/hooks/pre_gen.dart, very_good_flutter_plugin/hooks/test/pre_gen_test.dart
=> refactor(very_good_flutter_plugin): define versions in version.dart file

very_good_flutter_plugin/hooks/pubspec.yaml
Related to #38 
Changed derived from: `dart pub upgrade --tighten`.
=> feat(very_good_flutter_plugin): tighten hook dependencies

very_good_flutter_plugin/brick.yaml
=> chore(very_good_flutter_plugin): update bricks to Mason 0.1.0-dev.52

very_good_dart_package/CHANGELOG.md, very_good_dart_package/brick.yaml
=> chore(very_good_dart_package): v0.5.0

very_good_dart_cli/CHANGELOG.md, very_good_dart_cli/brick.yaml
Changes available in `CHANGELOG.md`
=> chore(very_good_dart_cli): v0.6.0

very_good_wear_app/.gitignore
Related to https://github.com/VeryGoodOpenSource/very_good_templates/issues/46
Adds a commit with [all previous contributors of Very Good Wear App](https://github.com/VeryGoodOpenSource/very_good_wear_app/graphs/contributors).
```txt
* chore(very_good_wear_app): add previous contributors
Co-authored-by: Renan Araujo <renanmatheuscorreiaaraujo@gmail.com>
Co-authored-by: Tom Arra <tarra3@gmail.com>
Co-authored-by: Scarlett Eliza <scarletteliza@gmail.com>
```
=> chore(very_good_wear_app): add previous contributors

very_good_wear_app/CHANGELOG.md, very_good_wear_app/brick.yaml
=> chore(very_good_wear_app): v0.4.0

very_good_flutter_plugin/hooks/pre_gen.dart
Removes some logs during `pre_gen`, they tend to spoil the output when generated through Very Good CLI.
=> refactor(very_good_flutter_plugin): remove logs during pre_gen

very_good_flutter_plugin/CHANGELOG.md, very_good_flutter_plugin/brick.yaml
=> chore(very_good_fluter_plugin): v0.7.1

very_good_flame_game/__brick__/{{project_name.snakeCase()}}/android/app/build.gradle, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/android/build.gradle, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/android/settings.gradle
=> fix(very_good_flame_game): deprecated imperative apply of Flutter's Gradle plugins

very_good_wear_app/__brick__/{{project_name.snakeCase()}}/android/app/build.gradle, very_good_wear_app/__brick__/{{project_name.snakeCase()}}/android/build.gradle, very_good_wear_app/__brick__/{{project_name.snakeCase()}}/android/settings.gradle
=> fix(very_good_wear_app): deprecated imperative apply of Flutter's Gradle plugins

very_good_dart_package/CHANGELOG.md, very_good_dart_package/brick.yaml
=> chore(very_good_dart_package): v0.5.1

very_good_flutter_package/CHANGELOG.md, very_good_flutter_package/brick.yaml
=> chore(very_good_flutter_package): v0.5.1

very_good_dart_cli/CHANGELOG.md, very_good_dart_cli/brick.yaml
=> chore(very_good_dart_cli): v0.6.1

very_good_flame_game/CHANGELOG.md, very_good_flame_game/brick.yaml
=> chore(very_good_flame_game): v0.6.1

very_good_core/CHANGELOG.md, very_good_core/brick.yaml, very_good_core/tool/release_ready.sh
=> chore(very_good_core): v0.7.0

very_good_dart_cli/CHANGELOG.md, very_good_dart_cli/brick.yaml, very_good_dart_cli/tool/release_ready.sh
=> chore(very_good_dart_cli): v0.7.0

very_good_wear_app/CHANGELOG.md, very_good_wear_app/brick.yaml, very_good_wear_app/tool/release_ready.sh
=> chore(very_good_wear_app): v0.5.0

very_good_flutter_plugin/CHANGELOG.md, very_good_flutter_plugin/brick.yaml, very_good_flutter_plugin/hooks/lib/version.dart, very_good_flutter_plugin/tool/release_ready.sh
=> chore(very_good_flutter_plugin): v0.8.0

.github/workflows/publish_very_good_core.yaml, .github/workflows/publish_very_good_dart_cli.yaml, .github/workflows/publish_very_good_dart_package.yaml, .github/workflows/publish_very_good_docs_site.yaml, .github/workflows/publish_very_good_flame_game.yaml, .github/workflows/publish_very_good_flutter_package.yaml, .github/workflows/publish_very_good_flutter_plugin.yaml, .github/workflows/publish_very_good_wear_app.yaml
=> ci: include publish workflows

very_good_flame_game/__brick__/{{project_name.snakeCase()}}/android/app/build.gradle, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/android/settings.gradle
=> chore: update Java version for Very Good Flame Game

very_good_core/__brick__/{{project_name.snakeCase()}}/android/app/build.gradle, very_good_core/__brick__/{{project_name.snakeCase()}}/android/settings.gradle
Fixes #120 by updating the Java versions. Also noticed the Kotlin versions were behind so updating that too.
=> chore: update Java versions on Very Good Core

very_good_core/CHANGELOG.md, very_good_core/brick.yaml
=> chore(very_good_core): v0.7.1

very_good_dart_cli/CHANGELOG.md, very_good_dart_cli/brick.yaml
=> chore(very_good_dart_cli): v0.7.1

very_good_dart_package/CHANGELOG.md, very_good_dart_package/brick.yaml
=> chore(very_good_dart_package): v0.6.1

very_good_flame_game/CHANGELOG.md, very_good_flame_game/brick.yaml
=> chore(very_good_flame_game): v0.7.1

very_good_flutter_package/CHANGELOG.md, very_good_flutter_package/brick.yaml
=> chore(very_good_flutter_package): v0.6.1

very_good_wear_app/CHANGELOG.md, very_good_wear_app/brick.yaml
=> chore(very_good_wear_app): v0.5.1

very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/example/{{#android}}android{{/android}}/build.gradle, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/example/{{#android}}android{{/android}}/gradle/wrapper/gradle-wrapper.properties
Related to #123
Updates [gradle](https://docs.flutter.dev/release/breaking-changes/android-java-gradle-migration-guide) to 7.6.1 using:
```sh
./gradlew wrapper --gradle-version=7.6.1
```
=> chore: update gradle to 7.6.1

very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/example/{{#android}}android{{/android}}/build.gradle, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/example/{{#android}}android{{/android}}/settings.gradle
Related to #123 
Updates Kotlin to 1.7.10 and AGP to 7.3.0.
=> chore: update example Kotlin and AGP

very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/example/{{#android}}android{{/android}}/app/build.gradle, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/example/{{#android}}android{{/android}}/build.gradle
Related to #123 
As per https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
=> chore: deprecate imperative apply of Flutter's Gradle plugins

.github/workflows/very_good_core_hooks.yaml
Analyze `lib` directory, which is currently not being analyzed.
=> ci(very_good_core): analyze hooks lib directory

very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{#android}}{{project_name.snakeCase()}}_android{{/android}}/android/build.gradle, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{#android}}{{project_name.snakeCase()}}_android{{/android}}/android/settings.gradle
=> chore: android flutter plugin to use recommended plugin DSL

very_good_core/hooks/lib/src/models/very_good_core_configuration.dart, very_good_core/hooks/test/src/models/very_good_core_configuration_test.dart
Start considering empty application id values ('') as empty and fallback to default.
=> fix: default id when application id is empty

very_good_dart_cli/CHANGELOG.md, very_good_dart_cli/brick.yaml
Related to https://github.com/VeryGoodOpenSource/_very_good_chores/issues/127
=> chore(very_good_dart_cli): v0.7.2

very_good_wear_app/CHANGELOG.md, very_good_wear_app/brick.yaml
Related to https://github.com/VeryGoodOpenSource/_very_good_chores/issues/127
=> chore(very_good_wear_app): v0.5.2

very_good_flutter_plugin/CHANGELOG.md, very_good_flutter_plugin/brick.yaml, very_good_flutter_plugin/hooks/lib/version.dart
Related to https://github.com/VeryGoodOpenSource/_very_good_chores/issues/127
=> chore(very_good_flutter_plugin): v0.8.2

very_good_flame_game/CHANGELOG.md, very_good_flame_game/brick.yaml
Related to https://github.com/VeryGoodOpenSource/_very_good_chores/issues/127
=> chore(very_good_flame_game): v0.7.2

very_good_flame_game/hooks/pubspec.yaml
Related to https://github.com/VeryGoodOpenSource/very_good_cli/pull/1094
=> chore: use git dependency over path dependency

very_good_flame_game/CHANGELOG.md, very_good_flame_game/brick.yaml
Fix related to https://github.com/VeryGoodOpenSource/very_good_cli/pull/1094
=> chore(very_good_flame_game): v0.7.3

.github/workflows/very_good_core.yaml, .github/workflows/very_good_dart_cli.yaml, .github/workflows/very_good_dart_package.yaml, .github/workflows/very_good_flame_game.yaml, .github/workflows/very_good_flutter_package.yaml, .github/workflows/very_good_flutter_plugin.yaml, .github/workflows/very_good_wear_app.yaml, tool/dependency_tightener/pubspec.yaml, very_good_core/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_core/hooks/pubspec.yaml, very_good_dart_cli/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_dart_cli/hooks/pubspec.yaml, very_good_dart_package/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_flame_game/hooks/pubspec.yaml, very_good_flutter_package/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_flutter_plugin/hooks/lib/version.dart, very_good_flutter_plugin/hooks/pubspec.yaml, very_good_wear_app/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_wear_app/hooks/pubspec.yaml
Updating to Flutter 3.24.0 and Dart 3.5.0. Fixes #176
=> chore: update to Flutter 3.24 and Dart 3.5

very_good_core/CHANGELOG.md, very_good_core/brick.yaml
Prepares release, updates in CONTRIBUTING.md
=> chore(very_good_core): v0.8.0

very_good_dart_cli/CHANGELOG.md, very_good_dart_cli/brick.yaml
=> chore(very_good_dart_cli): v0.8.0

very_good_dart_package/CHANGELOG.md, very_good_dart_package/brick.yaml
=> chore(very_good_dart_package): v0.7.0

very_good_flame_game/CHANGELOG.md, very_good_flame_game/brick.yaml
=> chore(very_good_flame_game): v0.8.0

very_good_flutter_plugin/CHANGELOG.md, very_good_flutter_plugin/brick.yaml, very_good_flutter_plugin/hooks/lib/version.dart
=> chore(very_good_flutter_plugin): v0.9.0

very_good_flutter_package/CHANGELOG.md, very_good_flutter_package/brick.yaml
=> chore(very_good_flutter_package): v0.7.0

very_good_wear_app/CHANGELOG.md, very_good_wear_app/brick.yaml
=> chore(very_good_wear_app): v0.6.0

very_good_flame_game/__brick__/{{project_name.snakeCase()}}/android/app/build.gradle
Resolves https://github.com/VeryGoodOpenSource/very_good_templates/issues/186
=> fix(very_good_flame_game): add closing } in build.gradle

very_good_flame_game/CHANGELOG.md, very_good_flame_game/brick.yaml
=> chore(very_good_flame_game): v0.8.1

very_good_core/hooks/lib/src/models/very_good_core_configuration.dart, very_good_core/hooks/pre_gen.dart, very_good_core/hooks/test/pre_gen_test.dart
Updates to reflect https://github.com/VeryGoodOpenSource/very_good_templates/pull/192 changes.
=> refactor: move current_year out from configuration

very_good_core/__brick__/{{project_name.snakeCase()}}/android/app/build.gradle, very_good_core/__brick__/{{project_name.snakeCase()}}/android/gradle/wrapper/gradle-wrapper.properties, very_good_core/__brick__/{{project_name.snakeCase()}}/android/settings.gradle, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/android/app/build.gradle, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/android/gradle/wrapper/gradle-wrapper.properties, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/android/settings.gradle, very_good_wear_app/__brick__/{{project_name.snakeCase()}}/android/app/build.gradle, very_good_wear_app/__brick__/{{project_name.snakeCase()}}/android/gradle/wrapper/gradle-wrapper.properties, very_good_wear_app/__brick__/{{project_name.snakeCase()}}/android/settings.gradle
Attempting the fixes proposed in https://github.com/VeryGoodOpenSource/very_good_cli/issues/1163 to help with out of the box Android apps.
=> fix: update android build versions

very_good_wear_app/CHANGELOG.md, very_good_wear_app/brick.yaml
0.7.0 release for `very_good_wear_app`. Part of https://github.com/VeryGoodOpenSource/very_good_templates/issues/206
=> chore(very_good_wear_app): v0.7.0

.github/workflows/publish_very_good_flame_game.yaml, very_good_flame_game/CHANGELOG.md, very_good_flame_game/brick.yaml
0.9.0 release for very_good_flame_game. Part of https://github.com/VeryGoodOpenSource/very_good_templates/issues/206
=> chore(very_good_flame_game): v0.9.0

.github/.cspell/dev_dictionary.txt, .github/workflows/publish_very_good_core.yaml, .github/workflows/publish_very_good_dart_cli.yaml, .github/workflows/publish_very_good_dart_package.yaml, .github/workflows/publish_very_good_docs_site.yaml, .github/workflows/publish_very_good_flutter_package.yaml, .github/workflows/publish_very_good_flutter_plugin.yaml, very_good_core/CHANGELOG.md, very_good_core/CONTRIBUTING.md, very_good_core/brick.yaml
0.9.0 release for `very_good_core`. Part of #206
=> chore(very_good_core): 0.9.0

.github/PULL_REQUEST_TEMPLATE.md, very_good_core/__brick__/{{project_name.snakeCase()}}/.github/PULL_REQUEST_TEMPLATE.md, very_good_dart_cli/__brick__/{{project_name.snakeCase()}}/.github/PULL_REQUEST_TEMPLATE.md, very_good_dart_package/__brick__/{{project_name.snakeCase()}}/.github/PULL_REQUEST_TEMPLATE.md, very_good_docs_site/__brick__/{{project_name.snakeCase()}}/.github/PULL_REQUEST_TEMPLATE.md, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/.github/PULL_REQUEST_TEMPLATE.md, very_good_flutter_package/__brick__/{{project_name.snakeCase()}}/.github/PULL_REQUEST_TEMPLATE.md, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/.github/PULL_REQUEST_TEMPLATE.md, very_good_wear_app/__brick__/{{project_name.snakeCase()}}/.github/PULL_REQUEST_TEMPLATE.md
Add test option to pull requests templates
=> feat: update pull request templates to add `test` type option

very_good_core/CHANGELOG.md, very_good_core/brick.yaml, very_good_core/tool/release_ready.sh
Part of #223. Releases Very Good Core 0.10.0
=> chore(very_good_core): v0.10.0

very_good_dart_package/CHANGELOG.md, very_good_dart_package/brick.yaml, very_good_dart_package/tool/release_ready.sh
Part of #224. Releases Very Good Dart Package 0.8.0
=> chore(very_good_dart_package): v0.8.0

very_good_docs_site/CHANGELOG.md, very_good_docs_site/brick.yaml, very_good_docs_site/tool/release_ready.sh
Part of #224 Releases Very Good Docs Site 0.0.4.
Also includes the release ready script which was missing from this package.
=> chore(very_good_docs_site): v0.0.4

very_good_flutter_package/CHANGELOG.md, very_good_flutter_package/brick.yaml, very_good_flutter_package/tool/release_ready.sh
Part of #224 Releases Very Good Flutter Package 0.8.0
=> chore(very_good_flutter_package): v0.8.0

very_good_flutter_plugin/CHANGELOG.md, very_good_flutter_plugin/brick.yaml, very_good_flutter_plugin/hooks/lib/version.dart, very_good_flutter_plugin/tool/release_ready.sh
Part of #224 Releases Very Good Flutter Plugin 0.10.0
=> chore(very_good_flutter_plugin): v0.10.0

very_good_wear_app/CHANGELOG.md, very_good_wear_app/brick.yaml, very_good_wear_app/tool/release_ready.sh
Part of #224 Releases Very Good Wear App 0.8.0
=> chore(very_good_wear_app): v0.8.0

very_good_flame_game/__brick__/{{project_name.snakeCase()}}/pubspec.yaml
Fixes this [workflow](https://github.com/VeryGoodOpenSource/very_good_templates/actions/runs/15415523263/job/43377291375?pr=243).
=> chore(very_good_flame_game): update to mockingjay 2.0.0

very_good_wear_app/CHANGELOG.md, very_good_wear_app/brick.yaml
Prepare release for very_good_wear_app 0.9.0.
=> chore(very_good_wear_app): v0.9.0

very_good_dart_cli/CHANGELOG.md, very_good_dart_cli/brick.yaml
Prepare release of very_good_dart_cli 0.10.0.
=> chore(very_good_dart_cli): v0.10.0

very_good_dart_package/CHANGELOG.md, very_good_dart_package/brick.yaml
Prepare release of very_good_dart_package 0.9.0.
=> chore(very_good_dart_package): v0.9.0

very_good_flutter_package/CHANGELOG.md, very_good_flutter_package/brick.yaml
Prepare release of very_good_flutter_package 0.9.0.
=> chore(very_good_flutter_package): v0.9.0

very_good_core/CHANGELOG.md, very_good_core/brick.yaml
Prepare release of very_good_core 0.11.0.
=> chore(very_good_core): v0.11.0

.github/workflows/very_good_dart_cli.yaml, very_good_dart_cli/__brick__/{{project_name.snakeCase()}}/lib/src/command_runner.dart, very_good_dart_cli/__brick__/{{project_name.snakeCase()}}/test/src/command_runner_test.dart
Adds a missing test to reach 100% coverage.
=> test(very_good_dart_cli): add missing test

very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/example/actions/check_platform_name/test/src/check_platform_name_test.dart, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/example/lib/main.dart
=> fix(very_good_flutter_plugin): linting issues

very_good_flutter_plugin/CHANGELOG.md, very_good_flutter_plugin/brick.yaml
Prepare release of very_good_flutter_plugin 0.11.1.
=> chore(very_good_flutter_plugin): v0.11.1

very_good_core/CHANGELOG.md, very_good_core/brick.yaml
Prepare release of very_good_core 1.0.0.
=> chore(very_good_core): v1.0.0

very_good_dart_package/CHANGELOG.md, very_good_dart_package/brick.yaml
Prepare release of `very_good_dart_package` 1.0.0.
=> chore(very_good_dart_package): v1.0.0

very_good_docs_site/CHANGELOG.md, very_good_docs_site/brick.yaml
Prepare release of `very_good_docs_site` 1.0.0.
=> chore(very_good_docs_site): v1.0.0

very_good_flame_game/CHANGELOG.md, very_good_flame_game/brick.yaml
Prepare release of `very_good_flame_game` 1.0.0.
=> chore(very_good_flame_game): v1.0.0

very_good_flutter_package/CHANGELOG.md, very_good_flutter_package/brick.yaml
Prepare release of `very_good_flutter_package` 1.0.0.
=> chore(very_good_flutter_package): v1.0.0

very_good_flutter_plugin/CHANGELOG.md, very_good_flutter_plugin/brick.yaml
Prepare release of `very_good_flutter_plugin` 1.0.0.
=> chore(very_good_flutter_plugin): v1.0.0

very_good_wear_app/CHANGELOG.md, very_good_wear_app/brick.yaml
Prepare release of very_good_wear_app 1.0.0.
=> chore(very_good_wear_app): v1.0.0

very_good_flame_game/__brick__/android/gradle/wrapper/gradle-wrapper.properties, very_good_flame_game/__brick__/android/settings.gradle
- fix(very_good_flame_game): deprecated android gradle plugin version
Related to https://github.com/VeryGoodOpenSource/very_good_cli/issues/1316
=> fix(very_good_flame_game): deprecated android gradle plugin version

very_good_core/__brick__/test/counter/view/counter_page_test.dart
- Fix inconsistencies in the `CounterPage` test with coverage when testing `const` constructors using the same approach we used in `very_good_core/__brick__/test/app/view/app_test.dart`
=> fix(very_good_core): testing coverage

.github/.cspell/words_dictionary.txt
- chore: update dictionary
- chore: update dictionary
=> chore: update dictionary
