.github/workflows/very_good_flutter_plugin.yaml, very_good_flutter_plugin/hooks/lib/version.dart, very_good_flutter_plugin/hooks/pubspec.yaml, very_good_flutter_plugin/tool/merge_coverage/pubspec.yaml
=> feat(very_good_flutter_plugin)!: bump version to 3.19.0

very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{#android}}{{project_name.snakeCase()}}_android{{/android}}/pubspec.yaml, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{#ios}}{{project_name.snakeCase()}}_ios{{/ios}}/pubspec.yaml, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/pubspec.yaml
Resolves #38 
Changes derived from generating a project and updating the template made after running:
```sh
flutter pub upgrade --tighten -C my_plugin && flutter pub upgrade --tighten -C my_plugin/example && flutter pub upgrade --tighten -C my_plugin_android && flutter pub upgrade --tighten -C my_plugin_ios && flutter pub upgrade --tighten -C my_plugin_linux && flutter pub upgrade --tighten -C my_plugin_macos && flutter pub upgrade --tighten -C my_plugin_platform_interface && flutter pub upgrade --tighten -C my_plugin_web && flutter pub upgrade --tighten -C my_plugin_windows
```
=> chore(very_good_flutter_plugin): tighten dependencies

very_good_dart_cli/__brick__/{{project_name.snakeCase()}}/lib/{{project_name.snakeCase()}}.dart, very_good_dart_cli/__brick__/{{project_name.snakeCase()}}/test/ensure_build_test.dart, very_good_dart_package/__brick__/{{project_name.snakeCase()}}/lib/{{project_name.snakeCase()}}.dart, very_good_flutter_package/__brick__/{{project_name.snakeCase()}}/lib/{{project_name.snakeCase()}}.dart, very_good_flutter_plugin/hooks/lib/src/cli/cli.dart, very_good_flutter_plugin/hooks/lib/version.dart, very_good_flutter_plugin/hooks/lib/very_good_flutter_plugin_hooks.dart, very_good_flutter_plugin/tool/merge_coverage/merge_coverage.dart
Removing named library from packages to adhere to [effective dart guidelines](https://dart.dev/effective-dart/style#dont-explicitly-name-libraries)
- [ X] 🗑️ Chore
=> refactor: remove explicitly named libraries

very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/example/actions/check_platform_name/lib/src/check_platform_name.dart, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/example/actions/check_platform_name/test/src/check_platform_name_test.dart
Added proper test cases for missing code coverage as noted in #40
=> test: very_good_flutter_plugin doesn't have full code coverage

.github/workflows/very_good_core.yaml, very_good_core/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_core/hooks/pubspec.yaml
Related to #96 
Updates the very_good_core template so it runs and uses on Flutter 3.22 with Dart 3.4. 
This change limits itself to make the project runnable. Amendments due to the new version (such as the serviceWorkerVersion warning, #98 ) are to be done in a follow-up pull requests.
=> chore(very_good_core): ensure template uses Flutter 3.22 with Dart 3.4

.github/workflows/very_good_dart_cli.yaml, very_good_dart_cli/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_dart_cli/hooks/pubspec.yaml
Updates the very_good_dart_cli template so it runs and uses Dart 3.4.
This change limits itself to make the project runnable. Amendments due to the new language version should be considered in follow up pull requests.
=> chore(very_good_dart_cli): ensure template uses Dart 3.4

.github/workflows/very_good_dart_package.yaml, very_good_dart_package/__brick__/{{project_name.snakeCase()}}/pubspec.yaml
Updates the very_good_dart_package template so it runs and uses Dart 3.4.
This change limits itself to make the project runnable. Amendments due to the new language version should be considered in follow up pull requests.
=> chore(very_good_dart_package): ensure template uses Dart 3.4

.github/workflows/very_good_flutter_package.yaml, very_good_flutter_package/__brick__/{{project_name.snakeCase()}}/pubspec.yaml
Updates the very_good_flutter_package template so it runs and uses on Flutter 3.22 with Dart 3.4.
This change limits itself to make the project runnable. Amendments due to the new Flutter or Dart version are to be done in a follow-up pull requests.
=> chore(very_good_flutter_package): ensure template uses Flutter 3.22 with Dart 3.4

.github/workflows/very_good_flame_game.yaml, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/lib/app/view/app.dart, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/pubspec.yaml
Updates the very_good_flame_game template so it runs and uses on Flutter 3.22 with Dart 3.4.
This change limits itself to make the project runnable. Amendments due to the new version (such as the serviceWorkerVersion warning, see #103 ) are to be done in a follow-up pull requests.
=> chore(very_good_flame_game): ensure template uses Flutter 3.22 with Dart 3.4

.github/workflows/very_good_wear_app.yaml, very_good_wear_app/__brick__/{{project_name.snakeCase()}}/lib/app/view/app.dart, very_good_wear_app/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_wear_app/__brick__/{{project_name.snakeCase()}}/test/app/view/app_test.dart, very_good_wear_app/hooks/pubspec.yaml
Updates the very_good_wear_app template so it runs and uses on Flutter 3.22 with Dart 3.4.
This change limits itself to make the project runnable. Amendments due to the new Flutter or Dart version are to be done in a follow-up pull requests.
=> chore(very_good_wear_app): ensure template uses Flutter 3.22 with Dart 3.4

.github/workflows/very_good_flutter_plugin.yaml, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{#android}}{{project_name.snakeCase()}}_android{{/android}}/pubspec.yaml, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{#ios}}{{project_name.snakeCase()}}_ios{{/ios}}/pubspec.yaml, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{#linux}}{{project_name.snakeCase()}}_linux{{/linux}}/pubspec.yaml, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{#macos}}{{project_name.snakeCase()}}_macos{{/macos}}/pubspec.yaml, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{#web}}{{project_name.snakeCase()}}_web{{/web}}/pubspec.yaml, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{#windows}}{{project_name.snakeCase()}}_windows{{/windows}}/pubspec.yaml, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/example/actions/check_platform_name/pubspec.yaml, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/example/pubspec.yaml, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/pubspec.yaml, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}_platform_interface/pubspec.yaml, very_good_flutter_plugin/hooks/lib/version.dart, very_good_flutter_plugin/hooks/pubspec.yaml
Updates the very_good_flutter_plugin template so it runs and uses on Flutter 3.22 with Dart 3.4.
This change limits itself to make the project runnable. Amendments due to the new version are to be done in a follow-up pull requests.
=> chore(very_good_flutter_plugin): ensure template uses Flutter 3.22 with Dart 3.4

very_good_flame_game/CHANGELOG.md, very_good_flame_game/brick.yaml, very_good_flame_game/tool/release_ready.sh
=> chore(very_good_flame_game): v0.7.0

very_good_core/__brick__/{{project_name.snakeCase()}}/android/app/src/main/AndroidManifest.xml, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/android/app/src/main/AndroidManifest.xml, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/example/{{#android}}android{{/android}}/app/src/main/AndroidManifest.xml, very_good_wear_app/__brick__/{{project_name.snakeCase()}}/android/app/src/main/AndroidManifest.xml
and wearable meta data in AndroidManifest.xml templates. Fixes #125
Discovered a missing space ahead of the `<application` in the AndroidManifest.xml. It affected creation of Flutter app (`create flutter_app`), and upon code inspection I also saw the same pattern in Flame Game and Flutter Plugin creation. Besides that towards the end of the Wear app creation manifest had missing single spaces for the `com.google.android.wearable.standalone` `meta-data` tag.
Ref https://github.com/VeryGoodOpenSource/very_good_cli/pull/1067 and https://github.com/VeryGoodOpenSource/very_good_cli/issues/1066
=> style: Adding extra space to the application opening tag

very_good_core/__brick__/{{project_name.snakeCase()}}/macos/Runner.xcodeproj/project.pbxproj, very_good_core/hooks/lib/src/models/apple_application_id.dart, very_good_core/hooks/lib/src/models/models.dart, very_good_core/hooks/lib/src/models/very_good_core_configuration.dart, very_good_core/hooks/pre_gen.dart, very_good_core/hooks/test/pre_gen_test.dart, very_good_core/hooks/test/src/models/apple_application_id_test.dart, very_good_core/hooks/test/src/models/very_good_core_configuration_test.dart
Related to https://github.com/VeryGoodOpenSource/very_good_templates/issues/154. Updating the macOS project so it also uses the application id.
=> feat: use application id on macOS project

.github/workflows/very_good_flame_game_hoosk.yaml, very_good_core/brick.yaml, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/android/app/build.gradle, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/android/app/src/debug/AndroidManifest.xml, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/android/app/src/main/AndroidManifest.xml, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/android/app/src/main/kotlin/{{org_name.pathCase()}}/MainActivity.kt, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/android/app/src/profile/AndroidManifest.xml, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/ios/Runner.xcodeproj/project.pbxproj, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/macos/Runner.xcodeproj/project.pbxproj, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/windows/runner/Runner.rc, very_good_flame_game/brick.yaml, very_good_flame_game/config.json, very_good_flame_game/hooks/analysis_options.yaml, very_good_flame_game/hooks/lib/src/models/models.dart, very_good_flame_game/hooks/lib/src/models/very_good_flame_game_configuration.dart, very_good_flame_game/hooks/lib/very_good_core_hooks.dart, very_good_flame_game/hooks/pre_gen.dart, very_good_flame_game/hooks/pubspec.yaml, very_good_flame_game/hooks/test/pre_gen_test.dart
=> feat(very_good_flame_game): allow use of application_id var

very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{#android}}{{project_name.snakeCase()}}_android{{/android}}/android/build.gradle, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{#android}}{{project_name.snakeCase()}}_android{{/android}}/android/src/main/AndroidManifest.xml, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/example/{{#android}}android{{/android}}/app/build.gradle, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/example/{{#android}}android{{/android}}/app/src/debug/AndroidManifest.xml, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/example/{{#android}}android{{/android}}/app/src/main/AndroidManifest.xml, very_good_flutter_plugin/__brick__/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}/example/{{#android}}android{{/android}}/app/src/profile/AndroidManifest.xml
Related to #155
From the [documentation](https://developer.android.com/guide/topics/manifest/manifest-element):
> In the Gradle-based build system, starting with AGP 7.3, don't set the package value in the source manifest file directly. For more information, see [Set the application ID](https://developer.android.com/studio/build/configure-app-module#set-application-id).
Current example AGP version is 7.3
=> chore: remove legacy package tag in AndroidManifest.xml

tool/dependency_tightener/pubspec.yaml
=> chore: add executable field

very_good_flame_game/__brick__/{{project_name.snakeCase()}}/windows/runner/Runner.rc, very_good_flame_game/hooks/pre_gen.dart, very_good_flame_game/hooks/pubspec.yaml, very_good_flame_game/hooks/test/pre_gen_test.dart
The primary purpose of this change is to ensure that the correct year is used for copyright statement.
- Added the clock package to manage and retrieve the current year.
- Updated the code related to copyright handling to use clock.now().year.
=> fix(flame_game): set current year copyright

.github/workflows/very_good_core.yaml, .github/workflows/very_good_dart_cli.yaml, .github/workflows/very_good_dart_package.yaml, .github/workflows/very_good_flame_game.yaml, .github/workflows/very_good_flutter_package.yaml, .github/workflows/very_good_flutter_plugin.yaml, .github/workflows/very_good_wear_app.yaml, tool/dependency_tightener/pubspec.yaml, very_good_core/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_core/hooks/pubspec.yaml, very_good_dart_cli/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_dart_cli/hooks/pubspec.yaml, very_good_dart_package/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_flame_game/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_flame_game/hooks/pubspec.yaml, very_good_flutter_package/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_flutter_plugin/hooks/lib/version.dart, very_good_flutter_plugin/hooks/pubspec.yaml, very_good_wear_app/__brick__/{{project_name.snakeCase()}}/pubspec.yaml, very_good_wear_app/hooks/pubspec.yaml
Closes #222. Moves templates to newest version of Flutter & Dart.
=> chore: update to Flutter 3.27 and Dart 3.6

very_good_core/__brick__/{{project_name.snakeCase()}}/android/app/build.gradle.kts
This pull request removes the explicit sourceSets configuration from the `android/app/build.gradle.kts` file in the Very Good Core template.
Previously, the configuration included the following block:
```
sourceSets.getByName("main") {
java.setSrcDirs(listOf("src/main/kotlin"))
}
```
This code overrides the default source directories for the Android build system, restricting it to look **only** in `src/main/kotlin`. As a result, it ignores `src/main/java`, which is where the `GeneratedPluginRegistrant.java` file is located — a file that’s essential for registering Flutter plugins.
By removing this block, we allow the Android build system to consider both `src/main/java` and `src/main/kotlin`, ensuring proper plugin registration.
This change also aligns the template with the [official …
=> fix(android): correct source sets to ensure plugin compatibility
